SELECT DB_NAME() AS DatabaseName, DATABASEPROPERTYEX('AMOS', 'Status') AS DBStatus 

IF EXISTS (SELECT NAME FROM MASTER.SYS.DATABASES
WHERE NAME = N'AMOS' AND STATE_DESC = 'ONLINE')
PRINT 'Database is online'
ELSE
PRINT 'Database is not online'

SELECT NAME,
STATE_DESC
FROM SYS.DATABASES